site_name: BGP Configuration Labs
docs_dir: docs
site_dir: _html
repo_url: https://github.com/bgplab/bgplab
site_description: Hands-on BGP labs using virtual devices
site_author: Ivan Pepelnjak, ipSpace.net AG
copyright: (C) 2023 Ivan Pepelnjak (ipSpace.net AG)
plugins:
- search
- include_dir_to_nav
nav:
- Overview:
  - index.md
  - 1-setup.md
  - "Custom Lab Infrastructure":
    - external/index.md
    - external/4-router.md
  - 3-upcoming.md
- "Getting Started":
  - "Setting Up BGP":
    - basic/1-session.md
    - basic/2-multihomed.md
    - basic/3-originate.md
    - basic/4-ipv6.md
    - basic/5-redistribute.md
  - "Protecting BGP Sessions":
    - "MD5 Passwords and GTSM": basic/6-protect.md
    - "TCP Autentication Option (TCP-AO)": basic/9-ao.md
  - "BGP in Larger Networks":
    - "Establish an IBGP Session": ibgp/1-edge.md
    - "Build a Transit Network with IBGP": ibgp/2-transit.md
  - "Advanced Topics":
    - basic/7-bfd.md
    - basic/8-aggregate.md
- "Simple Policies": policy/

#- "Getting Started":
#  - basic-session/README.md
#  - basic-multihomed/README.md
markdown_extensions: 
- footnotes
- abbr
- def_list
- admonition
- attr_list
- sane_lists
- smarty

exclude_docs: |
  LICENSE.md
  config/
  *.j2
theme:
  name: mkdocs
  custom_dir: _mkdocs_theme
  navigation_depth: 3
