site_name: BGP Configuration Labs
docs_dir: docs
site_dir: _html
plugins:
- search
- include_dir_to_nav
nav:
- Overview:
  - index.md
  - 1-setup.md
  - 2-manual.md
  - 3-upcoming.md
- "Getting Started": basic/
- "Simple Policies": policy/

#- "Getting Started":
#  - basic-session/README.md
#  - basic-multihomed/README.md
markdown_extensions: 
- footnotes
exclude_docs: |
  LICENSE.md
  config/
  *.j2
theme:
  name: mkdocs
  custom_dir: _mkdocs_theme
