site_name: BGP Configuration Labs
docs_dir: docs
site_dir: _html
repo_url: https://github.com/ipspace/bgplab
site_description: Hands-on BGP labs using virtual devices
site_author: Ivan Pepelnjak, ipSpace.net AG
copyright: (C) 2023 Ivan Pepelnjak (ipSpace.net AG)
plugins:
- search
- include_dir_to_nav
nav:
- Overview:
  - index.md
  - 1-setup.md
  - "Custom Lab Infrastructure":
    - external/index.md
    - external/4-router.md
  - 3-upcoming.md
- "Getting Started": basic/
- "Simple Policies": policy/

#- "Getting Started":
#  - basic-session/README.md
#  - basic-multihomed/README.md
markdown_extensions: 
- footnotes
- abbr
- def_list
- admonition
- attr_list
- sane_lists
- smarty

exclude_docs: |
  LICENSE.md
  config/
  *.j2
theme:
  name: mkdocs
  custom_dir: _mkdocs_theme
