site_name: BGP Configuration Labs
docs_dir: docs
site_dir: _html
plugins:
- search
- include_dir_to_nav
nav:
- Installation:
  - 1-setup.md
  - 2-manual.md
- "Getting Started": basic/

#- "Getting Started":
#  - basic-session/README.md
#  - basic-multihomed/README.md
markdown_extensions: 
- footnotes
exclude_docs: |
  LICENSE.md
  config/
  *.j2
#theme:
#  name: readthedocs
